### ISSUE TITLE
aws_s3_bucket.cluster-storage: Error deleting S3 Bucket: BucketNotEmpty: The bucket you tried to delete is not empty (status code: 409)

### ISSUE THREAD

**Issue by wooiliang** [microservices-today/IaC-dcos#139]
Getting this error when running terraform destroy. Have to delete it manually before running terraform destroy.

aws_s3_bucket.cluster-storage: Error deleting S3 Bucket: BucketNotEmpty: The bucket you tried to delete is not empty (status code: 409)

**Comment by kamoljan** [comment]
@wooiliang you will have to first empty the bucket

**Comment by wooiliang** [comment]
@kamoljan Terraform not able to empty the bucket automatically?

**Comment by kamoljan** [comment]
@wooiliang it is not designed in the first place, just for security reason. It could be with force command

**Comment by wooiliang** [comment]
Noted @kamoljan Thanks for the answer!
