### ISSUE TITLE
Resource Tag parts should be removed from resource names.

### ISSUE THREAD

**Issue by AmalQB** [microservices-today/IaC-dcos#28]
Names often have a length limit.
```
Errors:

  * aws_elb.master: "name" cannot be longer than 32 characters: "Microservice-Staging-Master-ELB-Terra"
```

**Comment by kamoljan** [comment]
@AmalQB, it is required by some monitoring or alerting systems. It is critical to have tags.

**Comment by kamoljan** [comment]
@AmalQB either need to trim or hash those long tags

**Comment by AmalQB** [comment]
@kamoljan Tags will be as it is now, we need to change the names

**Comment by alexraju** [comment]
LB names are now created from pre-tag and post-tag filtering out characters other than alphanumeric characters and hyphens. Also, trimming out pre_tag and post_tag to follow the maximum length constraint.
```
    lb_pre_tag = "${replace(replace(var.pre_tag, "/[^0-9a-zA-Z-]/",""), "/^(.{14}).*/","$1")}"
    lb_post_tag = "${replace(replace(var.post_tag, "/[^0-9a-zA-Z-]/",""), "/^(.{6}).*/","$1")}"
    ......
    name            = "${null_resource.alias.triggers.lb_pre_tag}-Master-${null_resource.alias.triggers.lb_post_tag}"
```
