### ISSUE TITLE
Installation failed with Terraform version 0.7.0

### ISSUE THREAD

**Issue by alexraju** [microservices-today/IaC-dcos#29]
Error loading config: Error loading /home/centos/IaC-dcos/agent-autoscaling.tf: Error reading config for aws_launch_configuration[dcos_agent_lc]: Invalid dot index found: 'var.instance_type.agent'. Values in maps and lists can be referenced using square bracket indexing, like: 'var.mymap["key"]' or 'var.mylist[1]'. in:

${var.instance_type.agent}

**Comment by kamoljan** [comment]
@alexraju is it still valid issue?

**Comment by alexraju** [comment]
@kamoljan Issue fixed with #51 .
