### ISSUE TITLE
Use data source instead of deprecated template files ; Terraform 0.7.0 migration

### ISSUE THREAD

**Issue by alexraju** [microservices-today/IaC-dcos#30]
Warnings:

  * template_file.master_user_data #2: using template_file as a resource is deprecated; consider using the data source instead

**Comment by kamoljan** [comment]
@alexraju is it still valid issue?

**Comment by alexraju** [comment]
@kamoljan Issues is partially fixed with #51. There is no way to add `count` meta-data with new `data source`. So, we haven't migrated some template_files having `count` meta-data with it. Planning to update this once they introduce `count` to `data source`. There is an open issue to track this. https://github.com/hashicorp/terraform/issues/7919

**Comment by kamoljan** [comment]
@alexraju thank you!

**Comment by neethugeorge** [comment]
Resolved by #93

**Comment by kamoljan** [comment]
@neethugeorge thank you!
