### ISSUE TITLE
User roles not getting deleted while destroying

### ISSUE THREAD

**Issue by swami701** [microservices-today/IaC-dcos#44]
Terraform destroy is not deleting the User roles

**Comment by kamoljan** [comment]
@swami701 can you share your error message?

**Comment by kamoljan** [comment]
@swami701 thank you very much for your bug report. 
It is currently is an open issue in [terrafor](https://github.com/hashicorp/terraform/issues/2761).

Can you please drop s3_role manually from your aws account?

**Comment by kamoljan** [comment]
@swami701 this issue was solved, I am going to close it.
