### ISSUE TITLE
Why so many ports are open in Master ELB?

### ISSUE THREAD

**Issue by kamoljan** [microservices-today/IaC-dcos#5]
HTTP	80	HTTP	80	N/A	N/A
TCP	443	TCP	443	N/A	N/A
TCP	2181	TCP	2181	N/A	N/A
TCP	2222	TCP	22	N/A	N/A
HTTP	5050	HTTP	5050	N/A	N/A
HTTP	8080	HTTP	8080	N/A	N/A
HTTP	8181	HTTP	8181	N/A	N/A

**Comment by kamoljan** [comment]
HTTPS	443	HTTPS	443

Should be good enough. Looks like even master listening on 443, which is cool :)

**Comment by alexraju** [comment]
Fixed with c2bea682d9f3e4a71bf4c675d2581aae0ba54d6a
