### ISSUE TITLE
`instance_type` should be configurable 

### ISSUE THREAD

**Issue by kamoljan** [microservices-today/IaC-dcos#7]
for example instance_type = "m4.large", it might not be the case for development or staging  enviroments.

**Comment by alexraju** [comment]
instance_type made configurable for bootstrap, master, public agent & private agent with default `m4.large`.
```
variable "instance_type" {
  description = "DCOS instance type"
  default = {
    "bootstrap" = "m4.large"
    "master" = "m4.large"
    "public-agent" = "m4.large"
    "agent" = "m4.large"
  }
}
```
