### ISSUE TITLE
Use aws marketplace API to approve CoreOS instance 

### ISSUE THREAD

**Issue by kamoljan** [microservices-today/IaC-dcos#77]

**Comment by alexraju** [comment]
@kamoljan 
tried to find ways to do the CoreOS instance subscription using aws marketplace API, but couldn't find any APIs for that.
Also, Terraform itself tried to automate this part some time ago. hashicorp/terraform: Issue #2956

**Comment by kamoljan** [comment]
@alexraju thank you!
